#### 1.导入numpy库并简写为np 
(提示: import … as …)

In [8]:
import numpy as np

#### 2.打印numpy的版本及配置说明
(提示: np.__version__, np.show_config)

In [35]:
np.__version__

'1.16.2'

In [14]:
np.show_config()

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/setup/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'E:/setup/anaconda\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/setup/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'E:/setup/anaconda\\Librar

#### 3.创建一个长度为10的空向量
(提示: np.zeros)

In [19]:
arr=np.zeros(10)

In [20]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.如何找到任何一数组的内存大小?
(提示:size, itemsize)

In [24]:
import sys

In [25]:
sys.getsizeof(arr)

176

In [34]:
np.size(arr)*arr.itemsize

80

#### 5. 如何从命令中找到numpy的add函数的说明文档 (提示np.info)

In [37]:
np.info(np.sum)

 sum(a, axis=None, dtype=None, out=None, keepdims=<no value>,
     initial=<no value>)

Sum of array elements over a given axis.

Parameters
----------
a : array_like
    Elements to sum.
axis : None or int or tuple of ints, optional
    Axis or axes along which a sum is performed.  The default,
    axis=None, will sum all of the elements of the input array.  If
    axis is negative it counts from the last to the first axis.

    .. versionadded:: 1.7.0

    If axis is a tuple of ints, a sum is performed on all of the axes
    specified in the tuple instead of a single axis or all the axes as
    before.
dtype : dtype, optional
    The type of the returned array and of the accumulator in which the
    elements are summed.  The dtype of `a` is used by default unless `a`
    has an integer dtype of less precision than the default platform
    integer.  In that case, if `a` is signed then the platform integer
    is used while if `a` is unsigned then an unsigned integer of the
    same pr

#### 6. 创建一个长度为10并且除了第五个值为1的空向量

In [38]:
arr=np.zeros(10)

In [40]:
arr[4]=1

In [41]:
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. 创建一个值域范围从10到49的向量
(提示:np.arange)

In [44]:
arr=np.arange(10,50)

In [45]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.反转一个向量(从头开始依次进行反转) 
(提示array[::-1])

In [54]:
arr[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. 创建一个3x3并且值从0到8的矩阵
(提示 reshape)

In [59]:
arr=np.arange(9).reshape((3,3))

In [61]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. 创建一个 10x10 的随机数组并找到它的最大值和最小值
(提示: min, max)

In [69]:
arr=np.random.randn(10,10)

In [70]:
arr

array([[-7.62768329e-01, -9.53499535e-02,  1.66352840e+00,
        -1.13434365e+00,  2.57623563e-01,  2.71150574e+00,
        -3.78106380e-01,  6.84003196e-01, -1.31648009e-02,
        -1.76399119e+00],
       [ 9.08755982e-01, -2.39852657e-01,  1.03479052e+00,
        -6.79283828e-04, -7.82896056e-01, -2.95378072e-01,
        -7.78836541e-03,  1.63517924e+00, -5.21415642e-01,
         1.17929672e+00],
       [-1.90491400e+00,  6.88722906e-01,  4.83515486e-02,
        -1.83098189e-01, -9.18533975e-01, -1.17003581e-01,
        -6.25734964e-01,  1.88843183e+00,  9.08305650e-01,
        -3.88308880e-01],
       [-9.09925284e-01,  1.13742315e-01, -1.09419329e+00,
         6.76751701e-01, -3.50498036e-01, -1.47440137e+00,
        -1.19735966e+00,  2.00986876e-01,  2.12337805e+00,
         5.46221776e-01],
       [-5.35019376e-01, -1.14884691e+00,  6.55201411e-01,
         6.45443826e-01, -2.04154514e-01, -8.46262946e-02,
         3.68271513e-01,  1.34517924e+00, -7.41948735e-01,
        -5.

In [71]:
max=arr.max()

In [72]:
max

2.711505738289985

In [73]:
min=arr.min()

In [74]:
min

-2.40096280989953

#### 11.  创建一个长度为30的随机向量并找到它的平均值
(提示: mean)

In [75]:
arr=np.random.randn(30)

In [76]:
arr.mean()

0.09903352879048757

#### 12. 对一个5x5的随机矩阵做归一化
(提示: (x-min)/(max - min)

In [77]:
arr=np.random.randn(5,5)

In [78]:
arr

array([[-2.46572136, -0.26291924,  0.22078181,  0.33461001, -0.15392543],
       [-0.60143209,  0.87644691,  0.59469547,  0.07210354,  0.68319693],
       [ 0.65883365,  0.19250728,  0.71942687,  1.49967453, -0.28522654],
       [ 1.5365067 ,  1.02107499,  0.60777926,  1.07076548, -0.81597013],
       [ 0.9899872 , -1.37554114, -0.6381149 ,  0.38113322,  0.83897052]])

In [79]:
max=arr.max();min=arr.min()

In [80]:
arr2=(arr-min)/(max-min)

In [81]:
arr2

array([[0.        , 0.55039395, 0.6712519 , 0.6996931 , 0.57762724],
       [0.46581285, 0.83507692, 0.76467827, 0.63410302, 0.78679132],
       [0.78070389, 0.6641872 , 0.79584376, 0.99079708, 0.54482023],
       [1.        , 0.87121381, 0.7679474 , 0.88362952, 0.4122082 ],
       [0.86344619, 0.27239333, 0.45664726, 0.71131743, 0.82571304]])

#### 13. 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？
(提示 np.dot)

In [82]:
arr1=np.arange(15).reshape(5,3)

In [87]:
arr2=np.arange(6).reshape(3,2)

In [88]:
print(arr1,'\n\n',arr2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]] 

 [[0 1]
 [2 3]
 [4 5]]


In [89]:
np.dot(arr1,arr2)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 14. 在给定标量时, 如何找到数组中最接近标量的值?
(提示:argmin)

In [90]:
x=np.arange(50)

In [96]:
y=13.22244

In [95]:
print(x,'\n\n',v)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49] 

 74.48511644125684


In [101]:
z=np.abs(x-y).argmin()

In [102]:
z

13

#### 15.如何找到一个数组中出现频率最高的值?
(提示: np.bincount, argmax)

In [107]:
arr=np.random.randint(0,10,50)

In [108]:
arr

array([6, 6, 4, 9, 2, 9, 7, 7, 7, 8, 6, 3, 8, 1, 5, 9, 2, 5, 5, 3, 5, 6,
       5, 2, 7, 0, 2, 6, 4, 1, 5, 2, 7, 2, 1, 8, 6, 8, 0, 0, 8, 1, 5, 1,
       5, 6, 8, 3, 6, 0])

In [110]:
arr.sort()

In [111]:
arr

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 4, 4, 5, 5,
       5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 8, 8, 8,
       8, 8, 8, 9, 9, 9])

In [116]:
np.bincount(arr).argmax()

5

16. 如何找到一个数组的第n个最大值?
(np.argsort)

In [121]:
arr=np.random.randint(0,100,10)

In [122]:
arr

array([93,  3, 61, 17,  9, 84, 87, 76, 56, 63])

In [128]:
n=3

In [130]:
arr[np.argsort(-arr)[n-1]]

84

#### 17. 如何通过滑动窗口计算一个数组的平均数?
(提示 np.cumsum)